# Authors: Blake Christierson and Nick Alger
# Copyright: MIT License (2026)
# Github: https://github.com/NickAlger/implicit_probing
"""Sphinx configuration for the implicit_probing documentation site.

API reference is generated by ``sphinx.ext.autosummary`` -- one page per public function, one page
per class, and (via the class template in ``_templates/autosummary``) one page per method. The
narrative guide pages are the hand-written Markdown in ``docs/`` rendered through ``myst-parser``. The
theme is pydata-sphinx-theme.

Install the docs toolchain with the ``[docs]`` extra and build with Sphinx::

    pip install -e ".[docs]"
    python -m sphinx -b html docs docs/_build/html

autosummary imports every documented module to introspect it, so the build environment must be able to
import implicit_probing *and* its optional hooks (numpy + dolfinx + jax); otherwise the FEniCS/JAX hook
pages fail to build. See the FEniCS install guide for dolfinx, and ``pip install ".[jax]"`` for jax.
"""
import os
import sys

# Make the in-tree package importable without installing it (repo root is the parent of docs/).
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import implicit_probing  # noqa: E402  (after sys.path tweak)

# -- Project information -----------------------------------------------------------------------------

project = "implicit_probing"
author = "Blake Christierson and Nick Alger"
copyright = "2026, Blake Christierson and Nick Alger"
version = implicit_probing.__version__
release = version

# -- General configuration ---------------------------------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",       # pull docstrings from the package
    "sphinx.ext.autosummary",   # one generated stub page per object (see docs/api/index.rst)
    "sphinx.ext.napoleon",      # tolerate Google/NumPy docstring sections if any are added later
    "sphinx.ext.intersphinx",   # cross-link to numpy's docs
    "sphinx.ext.viewcode",      # [source] links to highlighted source
    "myst_parser",              # render the narrative .md guide pages
]

autosummary_generate = True          # (re)generate the api/generated/*.rst stubs on every build
autodoc_typehints = "signature"      # keep type hints in the signature, next to the shape comments
add_module_names = False             # show ``probe``, not ``implicit_probing.probe``, as page titles

# MyST: the narrative pages use fenced code, pipe tables, and the odd colon-fence admonition.
myst_enable_extensions = ["colon_fence", "deflist"]
myst_heading_anchors = 3

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
}

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# -- HTML output (pydata-sphinx-theme) ---------------------------------------------------------------

html_theme = "pydata_sphinx_theme"
html_title = f"{project} {version}"
html_theme_options = {
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/NickAlger/implicit_probing",
            "icon": "fa-brands fa-github",
        },
    ],
    "show_toc_level": 2,
    "navigation_with_keys": True,
}
